spring:
  application:
    name: Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.204.224.233:23306/Electron_Service?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 200309
  servlet:
    multipart:
      enabled: true #启用multipart文件上传
      max-file-size: 500MB #最大单文件大小
      max-request-size: 500MB #最大HTTP请求
  data:
    redis:
      port: 26739
      password: 200309
      host: 129.204.224.233
server:
  port: 8866
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启自动驼峰命名
  mapper-locations: mapper/*.xml #扫描mapper文件路径
logging:
  level:
    com.ligg.electronservice: debug #SQL日志级别